version: 0.0
os: windows
files:
  - source: api/Ganymede.Api/deploy
    destination: C:\inetpub\wwwroot\dmapi
hooks:
  ApplicationStop:
    - location: applicationStop.bat
  ApplicationStart:
    - location: applicationStart.bat
