version: 0.2
environment_variables:
  plaintext:
    S3_BUCKET: "dm.jackschaible.ca"
phases:
  install:
    commands:
      - npm i
      - npm i -g @angular/cli
  build:
    commands:
      - ng build --prod --aot
  post_build:
    commands:
      - aws s3 cp dist/ganymede s3://${S3_BUCKET}/ --recursive
