version: 0.2
phases:
  build:
    commands:
      - cd api
      - dotnet publish -o deploy
artifacts:
  files:
    - applicationStop.bat
    - applicationStart.bat
    - appspec.yml
    - api/deploy/*
